### ISSUE TITLE
Kobo Book Importer?

### ISSUE THREAD

**Issue by cwmke** [mollykannn/kobo-book-exporter#195]
Hi! I'm wondering if you'd consider adding an import function for those that want to export from one device and import into another? Either way thanks for creating this great tool!

**Comment by mollykannn** [comment]
Hello, thank you for your suggestion 😊
I have the other project [Kobo2Notion](https://github.com/mollykannn/kobo2notion). It can export the Kobo highlight to Notion. It maybe fulfil your advice 😊.

**Comment by cwmke** [comment]
Thanks!
